---
title: "Week_3 605 assignment"
author: "Salma Elshahawy"
date: "1/21/2020"
output: 
  pdf_document: 
    extra_dependencies: ["geometry"]
    latex_engine: xelatex
    keep_tex: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem set_1

### (1) What is the rank of the matrix A?

$\begin{bmatrix} 1 & 2 & 3 & 4 \\ -1 & 0 & 1 & 3 \\ 0 & 1 & -2 & 1 \\ 5 & 4 & -2 & -3 \end{bmatrix}$

```{r}
a <- matrix(c(1,2,3,4,
              -1,0,1,3,
              0,1,-2,1,
              5,4,-2,-3), 4, byrow=T)
# a <- matrix(c(0,1,2,1,2,7,2,1,8), ncol = 3)
a
```

```{r}
a <- matrix(c(1,2,3,4,
              -1,0,1,3), 4, byrow=T)
a
```
```{r}
get_U <- function(a) {
  U = a
  n = ncol(a)
  m = nrow(a)
  if(m == n) {
    for (i in 1:n) {
      for (j in 2:m) {
        if(U[j,i] != 0 & j > i) {
          # Add multiples of the pivot row to each of the lower rows, 
          # so every element in the pivot column of the lower rows equals 0.
          mplier = U[[j,i]]/U[[i,i]]
          # reduce by reduction and subtitute in the U matrix
          U[j,] = U[j,] - mplier * U[i,]
        } else if (j == i) {
          U[j,] = U[j,] / U[[j,i]]
        }# end if
      } # end if 
    } # end for
  } else if(m < n) {
    for (i in 1:n) {
      for (j in 2:m) {
        if(U[j,i] != 0 & j > i) {
          U[i,] = U[i,] / U[[i,i]]
          # Add multiples of the pivot row to each of the lower rows, 
          # so every element in the pivot column of the lower rows equals 0.
          mplier = U[[j,i]]/U[[i,i]]
          # reduce by reduction and subtitute in the U matrix
          U[j,] = U[j,] - mplier * U[i,]
          
        } else if(U[j,i] != 0 & j == i) {
          U[i,] = U[i,] / U[[i,i]]
        } # end if
      } # end for
    } # end for
  } else if (m > n) {
    for (i in 1:n) {
      for (j in 2:m) {
        if(U[j,i] != 0 & j > i) {
          U[i,] = U[i,] / U[[i,i]]
          # Add multiples of the pivot row to each of the lower rows, 
          # so every element in the pivot column of the lower rows equals 0.
          mplier = U[[j,i]]/U[[i,i]]
          # reduce by reduction and subtitute in the U matrix
          U[j,] = U[j,] - mplier * U[i,]
          
        } else if(U[j,i] != 0 & j == i) {
          U[i,] = U[i,] / U[[i,i]]
        } # end if
      } # end for
    } # end for
  } # end if 
  return(round(U, digits = 1))
}

c = get_U(a)
c
```
```{r}
inter = function(cd) {
  rank = 0
  sol = as.array(colSums(cd))
  # [1]  1  3  6 10
  for (i in 1:length(sol)) {
    if(sol[i] != 0) {
      rank = rank + 1
    }
  }
  return(rank)
}

d = inter(c)
d
```



