---
title: "SElshahawy_Assign7"
author: "Salma Elshahawy"
date: "3/10/2020"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
    df_print: paged
  pdf_document:
    extra_dependencies: geometry
    keep_tex: yes
    latex_engine: xelatex
---

## Question_1

Let X1, X2, . . . , Xn be n mutually independent random variables, each of which is uniformly distributed on the integers from 1 to k. Let Y denote the minimum of the Xi’s. Find the distribution of Y.

```{r}
set.seed(10000)
k = 100
n = 10
y_dist <- replicate(3000, {
  y_i = min(sample(1:k, n, replace=TRUE))
})

hist(y_dist)
```

## Question_2

Your organization owns a copier (future lawyers, etc.) or MRI (future doctors). This machine has a manufacturer’s expected lifetime of 10 years. This means that we expect one failure every ten years. (Include the probability statements and R Code for each part.).

### a. 
What is the probability that the machine will fail after 8 years?. Provide also the expected value and standard deviation. Model as a geometric. (Hint: the probability is equivalent to not failing during the first 8 years..)

### b.
What is the probability that the machine will fail after 8 years?. Provide also the expected value and standard deviation. Model as an exponential.

### c. 
What is the probability that the machine will fail after 8 years?. Provide also the expected value and standard deviation. Model as a binomial. (Hint: 0 success in 8 years)

### d. 
What is the probability that the machine will fail after 8 years?. Provide also the expected value and standard deviation. Model as a Poisson.

